version: '3'

services:

  www:
    hostname: www
    build: './src/public/www'
    restart: always
    volumes:
      - './src/public/www/html:/usr/share/nginx/html'
      - './data/public:/usr/share/nginx/html/escola'
      - './data/upload:/usr/share/nginx/html/files'
    ports:
      - '80:80'

  panel:
    hostname: panel
    build: './src/public/panel'
    restart: always
    volumes:
      - './src/public/panel/html:/usr/share/nginx/html/panel'

  api_upload:
    hostname: api_upload
    build: './src/api/upload'
    restart: always
    volumes:
      - './src/api/upload:/go/src'
      - './src/commons:/escola/commons'
      - './data:/escola/data'

  api_users_login:
    hostname: api_users_login
    build: './src/api/users-login'
    restart: always
    volumes:
      - './src/api/users-login:/escola/app'
      - './src/commons:/escola/commons'
      - './data:/escola/data'

  api_users_register:
    hostname: api_users_register
    build: './src/api/users-register'
    restart: always
    volumes:
      - './src/api/users-register:/escola/app'
      - './src/commons:/escola/commons'
      - './data:/escola/data'
